component SudokuCell inherits Rectangle {
    in property <int> value;
    in property <int> cell_index;
    in property <bool> selected;
    
    width: 50px;
    height: 50px;
    background: selected ? blue : white;
    
    callback clicked(int);

    TouchArea {
        clicked => {
            root.clicked(root.cell_index);
        }
    }   

    Text {
        text: value;
        color: green;
    }
}

export component SudokuWindow inherits Window {
    in property <[int]> cells;
    property <[int]> rows: [0, 1, 2, 3, 4, 5, 6, 7, 8];
    property <[int]> cols: [0, 1, 2, 3, 4, 5, 6, 7, 8];
    property <int> selected_cell: -1;
    
    min-width: 400px;
    min-height: 400px;
    background: black;

    callback cell_clicked(int);
    
    GridLayout {
        for row in rows: Row {
            for col in cols: SudokuCell {
                property <int> index: row * 9 + col;
                value: cells[index];
                cell_index: index;
                selected: selected_cell == index;

                clicked(index) => {
                    root.cell_clicked(index);
                }
            }
        }
    }

    cell_clicked(index) => {
        selected_cell = index;
        debug(selected_cell);
    }
    
}
