component SudokuCell inherits Rectangle {
    in property <int> value;
    in property <int> cell_index;
    in property <bool> selected;
    in property <bool> show_right_border: false;
    in property <int> valid_row;

    property <[int]> valid_row_border: [18, 19, 20, 21, 22, 23, 24, 25, 26];

    width: 80px;
    height: 80px;
    background: selected ? skyblue : lightgrey;

    callback clicked(int);

    TouchArea {
        clicked => {
            root.clicked(root.cell_index);
        }
    }

    Text {
        font-size: 20px;
        text: value;
        color: black;
    }

    // Black right-border
    Rectangle {
        x: parent.width - 2px;
        width: show_right_border ? 2px : 0px;
        height: parent.height;
        background: black;
    }

    //Black bottom-border
    for row in valid_row_border: Rectangle {
        y: parent.height - 2px;
        width: parent.width;
        height: (row == valid_row) ? 2px : 0px;
        background: black;
    }

    //Beige borders
    Rectangle {
        x: parent.width - 1px;
        width: 1px;
        height: parent.height;
        background: navy;
    }

    Rectangle {
        y: parent.height - 1px;
        width: parent.width;
        height: 1px;
        background: navy;
    }

    in-out property <string> box_value;

    function is_valid_num(value: string) -> bool {
        return value == "1" ||
            value == "2" ||
            value == "3" ||
            value == "4" ||
            value == "5" ||
            value == "6" ||
            value == "7" ||
            value == "8" ||
            value == "9";
    }

    TextInput {
        text <=> box_value;
        input-type: number;
        read-only: true;

        key-pressed(event) => {
            if(root.is_valid_num(event.text)) {
                box_value = event.text;
                accept
            }
            reject
        }
        
        width: max(parent.width, self.preferred-width);
        vertical-alignment: center;

        private property <length> margin: 1rem;
        cursor-position-changed(cursor-position) => {
            if cursor-position.x + self.x < margin {
                self.x = - cursor-position.x + margin;
            } else if cursor-position.x + self.x > parent.width - margin - self.text-cursor-width {
                self.x = parent.width - cursor-position.x - margin - self.text-cursor-width;
            }
        }
    }
}

export component SudokuWindow inherits Window {
    in property <[int]> cells;
    property <[int]> rows: [0, 1, 2, 3, 4, 5, 6, 7, 8];
    property <[int]> cols: [0, 1, 2, 3, 4, 5, 6, 7, 8];
    property <int> selected_cell: -1;

    min-width: 400px;
    min-height: 400px;
    background: black;

    callback cell_clicked(int);

    GridLayout {
        for row in rows: Row {
            for col in cols: SudokuCell {
                property <int> index: row * 9 + col;
                value: cells[index];
                cell_index: index;
                selected: selected_cell == index;
                show_right_border: Math.mod(index, 3) == 2;
                valid_row: Math.mod(index, 27);

                clicked(index) => {
                    root.cell_clicked(index);
                }
            }
        }
    }

    cell_clicked(index) => {
        selected_cell = index;
        debug(selected_cell);
    }
}
